name: Swift

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  Coverage:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: xcodebuild test -destination 'platform=macOS,arch=x86_64' -scheme "ZIPFoundation" -derivedDataPath Build/ 
      - run: (xcrun xccov view --only-targets --report Build/Logs/Test/*.xcresult | grep -Eq  "ZIPFoundation.*100\.00%") && { exit 0; } || { echo '::error Please make sure that the test suite covers all framework code paths.'; exit 1; }
